### ISSUE TITLE
Support 2 crops variable

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/idh-pdcportal#30]
1. Restructure the sentence so that we are not asserting that all farmers cultivate the focus crop
    - text: This dashboard is created from the primary data of `count_of_data` farmers in `country`. This data was collected during the SDM generation for `name_of_compay`, focusing on `name_of_crops` farmers. 
    - this change is for all condition not only multi crop. 
2. In the case of multi-crops in a single file, conditionally show a pie chart. The data will come from a pre-existing variable
   - Add `flag` to data config, to define that data has 2 crops

---

Variable `focus_crop_xxx`
for example, for CHC Zambia it has a crop focus_crop_maize_soybean and that capture these responses: yes, only maize|yes, maize and soybean|yes, only soybean|none of the above

**Comment by joycarpediem** [comment]
@wayangalihpratama , on hovering over the pie chart it shows the "series0" along with the option

**Comment by joycarpediem** [comment]
change donut to https://echarts.apache.org/examples/en/editor.html?c=data-transform-sort-bar
