### ISSUE TITLE
Data upload feedback -- Joy

### ISSUE THREAD

**Issue by joycarpediem** [akvo/idh-pdcportal#6]
See attachment
[screencapture-idh-demo-tc-akvo-org-home-2022-01-10-12_09_54.pdf](https://github.com/akvo/idh-pdcportal/files/7838468/screencapture-idh-demo-tc-akvo-org-home-2022-01-10-12_09_54.pdf)

**Comment by wayangalihpratama** [comment]
- [ ] Home page: Add title "Number of Users" to Map Chart 
- [ ] Home page: add Survey Conducted date to config if there's no date in the survey (dataset table)
- [ ] Overview/Country page: refactor project jumbotron to a dropdown list (design in pdf)
- [ ] Add text/an no data image for each missing chart

**Comment by wayangalihpratama** [comment]
- [ ] Update no data alert text to "This variable is not collected as part of data collection activity."

**Comment by wayangalihpratama** [comment]
- [ ] Hide submission date on Home table
